import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useEffect, useState} from 'react'
import Card from "../components/Card";

export default function Home() {
    const [count, setCount] = useState(0)
    const [todolist, setTodolist] = useState(["toto", "tata", "titi"])
    const [newElement, setNewElement] = useState()
    const [editableTodo, setEditableTodo] = useState()
    const [color, setColor] = useState('white')

    useEffect(() => {
        count >= 1 && setColor('red')
    }, [count])

    useEffect(() => {
        localStorage.setItem("todos", todolist)
        return () => {
            localStorage.clear()
        }
    }, [todolist])

    /**
     * Permet l'edition de la tache
     * @param todo
     * @param i
     */
    const editTask = (todo, i) => {
        setEditableTodo(i)
    }

    /**
     * Enregistre les modifications de la tache
     * @param e
     */
    const handleChange = (e) => {
        let copyTodolist = [...todolist];
        copyTodolist[editableTodo] = e.target.value;
        setTodolist(copyTodolist);
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
          <h1>Hello</h1>
          <h3>count: { count }</h3>
          <button style={{backgroundColor : color}} onClick={() => setCount(count + 1)}>Ajouter</button>
          <br />
          {
              todolist.length > 0 &&  (
                  todolist.map((todo, i) => {
                      return(
                          <div key={i}>
                              <input type="text" value={todo} disabled={editableTodo !== i} onChange={(e) => handleChange(e)} />
                              <button onClick={() => editTask(todo, i)}>{editableTodo !== i ? 'Edit' : 'In update'}</button>
                              <button onClick={() => setTodolist(todolist.filter((todo, index) => index !== i))}>Supprimer</button>
                          </div>
                      )
                  })
              )
          }
          <br />
          <div>
              <input type="text" value={newElement} onChange={(event) => setNewElement(event.target.value)} />
              <input type="button" value="Submit" onClick={() => setTodolist([...todolist, newElement])}/>
          </div>

          <Card title="Jolyne Kujoh" desc="Stand : stone ocean" image="https://pbs.twimg.com/media/E8HMAAgWQAAZc6e.jpg" price="100060 euros" />
      </main>
    </div>
  )
}
